### ISSUE TITLE
Nodemailer and Select branch

### ISSUE THREAD

**Issue by baljinderxd** [vyom153069/Automating-the-result#1]
1)Add npm install nodemailer in readme instructions as it was not installed with command npm install.
2)Select course(eg. B.TECH) instead of select branch in credentials.json .

**Comment by vyom153069** [comment]
Thank you @baljinderxd I will look at this 
Or if you want to do this then go ahead 👍👍

**Comment by baljinderxd** [comment]
> Or if you want to do this then go ahead 👍👍

Sure will create a PR 👍
